[phases.setup]
nixPkgs = ["php82", "composer", "nodejs-22_x"]

[phases.install]
cmds = [
    "composer install --optimize-autoloader --no-scripts --no-interaction",
    "npm ci",
    "npm prune --omit=dev --ignore-scripts"
]

[phases.build]
cmds = [
    "npm run build",
    "mkdir -p storage/framework/{sessions,views,cache,testing} storage/logs bootstrap/cache && chmod -R a+rw storage",
    "php artisan config:cache",
    "php artisan event:cache",
    "php artisan route:cache",
    "php artisan view:cache"
]

[start]
cmd = "/start-container.sh"
